"use strict";

module.exports = function routesPlugin(fastify, opts, next) {
  fastify.register(require("./role-route"));
  fastify.register(require("./role-permission-route"));
  fastify.register(require("./employee-route"));
  fastify.register(require("./login-route"));
  fastify.register(require("./page-route"));
  fastify.register(require("./user-route"));
  fastify.register(require("./upload-route"));
  fastify.register(require("./company-route"));
  fastify.register(require("./department-route"));
  fastify.register(require("./designation-route"));
  fastify.register(require("./expo-route"));
  fastify.register(require("./product-route"));
  fastify.register(require("./product-enquiry-route"));
  fastify.register(require("./dashboard-route"));
  fastify.register(require("./vehicle-type-route"));
  fastify.register(require("./vehicle-route"));
  fastify.register(require("./package-type-route"));
  fastify.register(require("./holiday-route"));
  fastify.register(require("./staff-attendance-route"));
  fastify.register(require("./customer-route"));
  fastify.register(require("./office-center-route"));
  fastify.register(require("./location-route"));
  fastify.register(require("./booking-route"));
  fastify.register(require("./expence-type-route"));
  fastify.register(require("./opening-balance-routes"));
  fastify.register(require("./expense-route"));
  fastify.register(require("./expense-payment-routes"));
  next();
};
