"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "pages",
      [
        {
          id: 1,
          page_id: "09ea6d44-a9d2-44b8-86b6-6560e33447ed",
          is_title: 1,
          title: "Dashboard",
          parent_id: null,
          page_name: null,
          page_url: null,
          icon_name: null,
          access_ids: null,
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          page_id: "51b8f024-021d-4fe6-a0f1-c09a7545dea2",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Dashboard",
          page_url: "/",
          icon_name: "fe-home",
          access_ids: "1",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          page_id: "4be5d482-4515-4883-b057-4c788f20a225",
          is_title: 1,
          title: "Master Menu",
          parent_id: null,
          page_name: null,
          page_url: null,
          icon_name: null,
          access_ids: null,
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          page_id: "a3ac0142-6440-4e2e-9ff3-80d0e24b0573",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Customer",
          page_url: "/master/customer",
          icon_name: "fe-users",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          page_id: "4d2b61bd-6228-47f8-bdb1-3a5102906871",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Employee",
          page_url: "/master/employee",
          icon_name: "fe-user",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          page_id: "4a586a35-10ef-41e9-bc60-e61db53d1b69",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Role",
          page_url: "/master/role",
          icon_name: "fe-lock",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          page_id: "d6c98aa9-b746-46ee-a61e-001f5fd75d33",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Branch",
          page_url: "/master/branch",
          icon_name: "fe-map-pin",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          page_id: "07ac38b9-7358-4e80-8fa1-80b270713a48",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Group",
          page_url: "/master/group",
          icon_name: "fe-layers",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          page_id: "ebc446cb-270b-4529-97a8-58ec65efe057",
          is_title: 1,
          title: "Main Menu",
          parent_id: null,
          page_name: null,
          page_url: null,
          icon_name: null,
          access_ids: null,
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          page_id: "2537009c-8de3-47f1-a5f9-88cc423a7d51",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Group Member",
          page_url: "/join/group-member",
          icon_name: "fe-friends",
          access_ids: "1,2,3,4,7",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          page_id: "e70582ab-a0d3-4d4c-8db7-1c25e7d3bc24",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Chit Estimate",
          page_url: "/join/chit-estimate",
          icon_name: "fe-check-square",
          access_ids: "1,2,3,4,6",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          page_id: "0fff0e55-af59-4255-b3fb-a6d12959153d",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Auction",
          page_url: "/join/auction",
          icon_name: "fe-gavel",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          page_id: "2c11cff6-1994-4aba-978e-a3661280fe09",
          is_title: 1,
          title: "Chit Transaction",
          parent_id: null,
          page_name: null,
          page_url: null,
          icon_name: null,
          access_ids: null,
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          page_id: "62fb1f24-e5ae-44b0-8a3e-3db47cf68aa3",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Chit Collection",
          page_url: "/chit-transaction/collection",
          icon_name: "fe-money",
          access_ids: "1,2,3,4,6",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          page_id: "924ec3ba-b5bd-4ba7-89d0-a184176b88cf",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Setilments",
          page_url: "/chit-transaction/setilments",
          icon_name: "fe-receipt",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          page_id: "443b581d-e65a-4a97-b35c-70a68745bbfd",
          is_title: 1,
          title: "Reports",
          parent_id: null,
          page_name: null,
          page_url: null,
          icon_name: null,
          access_ids: null,
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          page_id: "8e3c8f14-093f-4dcd-8549-959714617eee",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Member Report",
          page_url: "/reports/member-report",
          icon_name: "fe-chart",
          access_ids: "1,5",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          page_id: "d539d0e3-dccb-476b-9d30-74a70f8ea9c7",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Group Report",
          page_url: "/reports/group-report",
          icon_name: "fe-chart",
          access_ids: "1,5",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          page_id: "b07a0c2b-77a1-42f0-af1c-ec3d8100eac0",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Collection Agent Report",
          page_url: "/reports/collection-agent-report",
          icon_name: "fe-chart",
          access_ids: "1,3",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          page_id: "214dcc04-f181-4530-ab60-a656157e31ab",
          is_title: 0,
          title: null,
          parent_id: null,
          page_name: "Settilment Report",
          page_url: "/reports/settilment-report",
          icon_name: "fe-chart",
          access_ids: "1,2,3,4",
          is_active: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("pages", null, {});
  },
};
